export const GET_CHARACTER='GET_CHARACTER'
export const ADD_CHARACTER ="ADD_CHARACTER"
export const DELETE_CHARACTER ="DELETE_CHARACTER"
export const CHARACTER_DETAIL = "CHARACTER_DETAIL"
export const ADDFAV="ADDFAV"
export const REMOVEFAV="REMOVEFAV"